apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: messaging-stomp-websocket
  name: messaging-stomp-websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-stomp-websocket
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: messaging-stomp-websocket
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "12345"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/lgypro/messaging-stomp-websocket:v1
        name: spring-boot-hello-world
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 2000Mi
        env:
        - name: JAVA_OPTS
          value: "-javaagent:./agent/jmx_prometheus_javaagent-0.19.0.jar=12345:./agent/config.yaml"
      imagePullSecrets:
      - name: my-secret
